site_url: https://nexuscognitive.com

display_url: https://nexuscognitive.com

logo_url: https://nexuscognitive.com/images/logo.svg

backend:
  name: github
  branch: master
  repo: Nexus-Cognitive/website
  base_url: https://guarded-dawn-25112.herokuapp.com/

publish_mode: editorial_workflow

media_folder: static/images

public_folder: /images

collections:
  - name: authors
    label: Authors
    label_singular: Author
    folder: content/authors
    create: true
    extension: json
    fields:
      - name: title
        label: Name
        widget: string
      - name: position
        label: Position
        widget: string
      - name: partner
        label: Partner
        widget: boolean
        default: false
      - name: email
        label: Email
        widget: string
      - name: image
        label: Image
        widget: relation
        collection: images
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: linkedIn
        label: LinkedIn URL
        widget: string
      - name: order
        label: Order
        widget: number
        required: false
  - name: categories
    label: Categories
    label_singular: Category
    folder: content/categories
    create: true
    extension: json
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: string
  - name: colors
    label: Colors
    label_singular: Color
    folder: content/colors
    create: true
    extension: json
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: string
  - name: focuses
    label: Focuses
    label_singular: Focus
    folder: content/focuses
    create: true
    extension: json
    fields:
      - name: title
        label: Title
        widget: string
  - name: images
    label: Images
    label_singular: Image
    folder: content/images
    create: true
    extension: json
    fields:
      - name: title
        label: Title
        widget: string
      - name: src
        label: File
        widget: image
      - name: alt
        label: Alternate Description
        widget: string
      - name: width
        label: Width
        widget: number
      - name: height
        label: Height
        widget: number
  - name: services
    label: Services
    label_singular: Service
    folder: content/services
    create: true
    extension: json
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: string
  - name: insights
    label: Insights
    label_singular: Insight
    folder: content/insights
    create: true
    extension: md
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: string
      - name: body
        label: Body
        widget: markdown
        buttons:
          - bold
          - italic
          - code
          - link
          - heading-two
          - heading-three
          - heading-four
          - heading-five
          - heading-six
          - quote
          - bulleted-list
          - numbered-list
      - name: cover
        label: Cover
        widget: relation
        collection: images
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: publish
        label: Publish
        widget: datetime
        format: YYYY-MM-DDTHH:mm:ssZ
        picker_utc: true
        time_format: false
      - name: feature
        label: Feature
        widget: boolean
        default: true
      - name: authors
        label: Authors
        label_singular: Author
        widget: relation
        collection: authors
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: true
      - name: categories
        label: Categories
        label_singular: Category
        widget: relation
        collection: categories
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: true
  - name: slides
    label: Slides
    label_singular: Slide
    folder: content/slides
    create: true
    extension: json
    fields:
      - name: title
        label: Title
        widget: string
      - name: body
        label: Body
        widget: markdown
      - name: backgroundColor
        label: Background Color
        widget: relation
        collection: colors
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: image
        label: Image
        widget: relation
        collection: images
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: video
        label: Video
        widget: relation
        collection: videos
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: order
        label: Order
        widget: number
  - name: solutions
    label: Solutions
    label_singular: Solution
    folder: content/solutions
    create: true
    extension: md
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: Description
        widget: string
      - name: body
        label: Body
        widget: markdown
        buttons:
          - bold
          - italic
          - code
          - link
          - heading-two
          - heading-three
          - heading-four
          - heading-five
          - heading-six
          - quote
          - bulleted-list
          - numbered-list
      - name: client
        label: Client
        widget: string
      - name: project
        label: Project
        widget: string
      - name: amount
        label: Amount
        widget: string
      - name: problem
        label: Problem
        widget: string
      - name: cover
        label: Cover
        widget: relation
        collection: images
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: publish
        label: Publish
        widget: datetime
        format: YYYY-MM-DDTHH:mm:ssZ
        picker_utc: true
        time_format: false
      - name: authors
        label: Authors
        label_singular: Author
        widget: relation
        collection: authors
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: true
      - name: categories
        label: Categories
        label_singular: Category
        widget: relation
        collection: categories
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: true
  - name: strategies
    label: Strategies
    label_singular: Strategy
    folder: content/strategies
    create: true
    extension: json
    fields:
      - name: title
        label: Title
        widget: string
      - name: titleColor
        label: Title Color
        widget: relation
        collection: colors
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: body
        label: Body
        widget: markdown
      - name: bodyColor
        label: Body Color
        widget: relation
        collection: colors
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: backgroundColor
        label: Background Color
        widget: relation
        collection: colors
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: services
        label: Services
        label_singular: Service
        widget: relation
        collection: services
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: true
      - name: image
        label: Image
        widget: relation
        collection: images
        display_fields:
          - title
        value_field: '{{slug}}'
        search_fields:
          - title
        multiple: false
      - name: order
        label: Order
        widget: number
