export * as Article from '@/interfaces/article'
export * as Author from '@/interfaces/author'
export * as Category from '@/interfaces/category'
export * as Client from '@/interfaces/client'
export * as Image from '@/interfaces/image'
export * as Series from '@/interfaces/series'
